<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;
function ecobar_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {

if ($form_id == 'node_location_form' || $form_id == 'node_location_edit_form') {
$form['advanced']['#access'] = false;  
$form['status']['#access'] = false;  

ksm($form);
ksm($form_id); 
}


}  